[package]
name = "codedjimmy/tgframework"
version = "0.1.7"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A simple Roblox networking framework designed and managed by the T:Riza Corporation."
authors = ["Jimmy C."]

[dependencies]
bettersignal = "codedjimmy/bettersignal@0.1.1"
tnet = "codedjimmy/tnet@0.1.3"
tgframework = "codedjimmy/tgframework@0.1.5"