[package]
name = "codedjimmy/tgframework"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A simple Roblox networking framework designed and managed by the T:Riza Corporation."
authors = ["Jimmy C."]

[dependencies]
